name: Build

on:
  push:
    tags:
      - 1.*

jobs:
  build:
    name: Build App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build (Windows)
      if: ${{ runner.os == 'windows' }}
      run: |
        pyinstaller build.spec

    - name: Build (macOS)
      if: ${{ runner.os == 'macos' }}
      run: |
        pyinstaller build.spec
        
    - name: Build (Linux)
      if: ${{ runner.os == 'linux' }}
      run: |
        pyinstaller build.spec
        
    - name: Upload (Windows)
      if: ${{ runner.os == 'windows' }}
      uses: actions/upload-artifact@v3
      with:
        name: BangumiRenamer_windows
        path: |
          dist/*.exe

    - name: Upload (macOS)
      if: ${{ runner.os == 'macos' }}
      uses: actions/upload-artifact@v3
      with:
        name: BangumiRenamer_mac_x86
        path: |
          dist/*.app

    - name: Upload (Linux)
      if: ${{ runner.os == 'linux' }}
      uses: actions/upload-artifact@v3
      with:
        name: BangumiRenamer_linux
        path: |
          dist/*
